---
- name: reboot host
  ansible.builtin.reboot:
    msg: "{{ reboot_msg }}"
    pre_reboot_delay: "{{ reboot_pre_delay }}"
    reboot_timeout: "{{ reboot_timeout }}"
    post_reboot_delay: 10
    test_command: uptime
